- README.md
- build/common/config/.golangci.yml
- pkg/templates/clusterconfig_funcs.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
The custom delimiter support will allow distinguishing between multiple kinds of templates in
the same YAML file (e.g. `{{` vs `{{hub`).
Additionally, the template context support will allow the user to use the context of the policy being resolved in their templates. For example, they may use `.ClusterName` as a variable in their templates to reference the target cluster name that this template is being generated for.
> Add support for custom delimiters and template contexts

- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This was an oversight in:
https://github.com/open-cluster-management/go-template-utils/commit/c1db298d62d28738476a7c6ed5315d4f148ad0bb
> Require a Kubernetes configuration when instantiating the resolver

- pkg/templates/templates.go
- pkg/templates/templates_test.go
This makes the API more intuitive as you don't need to unmarshal
the JSON first, which is the most common format in hand when using this
library.
Additionally, it makes the API consistent since HasTemplate and
ResolveTemplate now both accept the same type as input.
> Modify ResolveTemplate to accept a JSON string

- pkg/templates/generic_lookup_func.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates_test.go
When the namespace is restricted, if the provided namespace is not set,
default to the restricted namespace for convenience.
> Default the namespace to the lookupNamespace when set

- pkg/templates/clusterconfig_funcs.go
- pkg/templates/clusterconfig_funcs_test.go
In commit 612affb, an attempt was made to restrict fromClusterClaim to a
specific namespace when the namespace is restricted (LookupNamespace).
The issue is that ClusterClaim is a cluster resource and not a namespace
resource so this approach did not work.
This commit makes it so that fromClusterClaim raises an error when the
namespace is restricted (LookupNamespace).
> Disable fromClusterClaim when namespace restrictions are set

- pkg/templates/templates.go
- pkg/templates/templates_test.go
AdditionalIndentation sets the number of additional spaces to be added
to the input number to the indent method. This is useful in situations
when the indentation should be relative to a logical starting point in
a YAML file.
> Add the AdditionalIndentation configuration option

- pkg/templates/clusterconfig_funcs.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
Instead of duplicating the configuration fields in TemplateResolver, it now holds on to the Config object itself and refers to that.
> Refactor the TemplateResolver type to not duplicate config fields

- pkg/templates/templates.go
- pkg/templates/templates_test.go
This resolves the edge case where a user has autoindent in the key of
a map. For example:
```yaml
data:
autoindent-test: '{{ "hello\nworld" | autoindent }}'
```
> Make the autoindent regex stricter

- .gitignore
- README.md
- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
The protect template function encrypts any string with AES-CBC
encryption. When enabled, the `fromSecret` template function also
returns an encrypted value.
A follow-up commit will add the decryption functionality.
Resolves:
https://github.com/stolostron/backlog/issues/18703
> Add the protect template function

- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This automatically detects strings in the format of `$ocm_encrypted:<base64 of encrypted string>` and replaces them with the original plaintext.
The second commit adds concurrency for the decryption process. Having it as a separate commit allows us to easily remove it if the squad to decides against it.
Resolves:
https://github.com/stolostron/backlog/issues/18705
> Add automatic decryption

- pkg/templates/templates.go
- pkg/templates/templates_test.go
Checks for the presence of `fromSecret` and/or `protect` template functions (it assumes encryption is already enabled if this check is being done).
This is for implementing the `protect` function so that we only generate secrets and initialization vectors when required:
- https://github.com/stolostron/backlog/issues/18712
> Add `UsesEncryption` method

- go.mod
This is due to the breaking change in the HasTemplate function.
> Update the module version to v2

- pkg/templates/templates.go
- pkg/templates/templates_test.go
This allows the template resolver to instantiate without the AES Key or Initialization Vector so that templates can be processed and the key and vector can be set on demand when an encrypted template function is discovered.
For:
- https://github.com/stolostron/backlog/issues/18712
Dependency for:
- https://github.com/stolostron/governance-policy-propagator/pull/160
> Add setter for EncryptionConfig

- pkg/templates/generic_lookup_func.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
The `ResolveTemplate` method will still function the same way except
that an error is also returned along with the resolved template when a
`lookup` template function call references an unknown API resource (e.g.
a CRD isn't installed). This lets the caller optionally choose to
refresh the `KubeAPIResourceList` value and try to resolve the templates
again.
Relates:
https://github.com/stolostron/backlog/issues/20382
> Return an error when a lookup references an unknown API resource

- pkg/templates/templates.go
- pkg/templates/templates_test.go
When a template fails to resolve likely due to `KubeAPIResourceList`
being out of date, return a specific error.
This is a follow-up to d15e3d46ea197ebdb88cb108da008615651a0888.
Relates:
https://github.com/stolostron/backlog/issues/20382
> Return an additional specific error for a template resolve failure

- .github/workflows/linters.yml
- .github/workflows/unit-tests.yml
Release branch tests are not working because the linting and unit
testing are not being run, but are expected.
Signed-off-by: Gus Parvin <gparvin@redhat.com>
> Tests are waiting forever in the release branches

- README.md
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This adds the toLiteral template function which simply removes the surrounding quotes around the template.
This enables a user to use a JSON string from a ConfigMap as it is.
Relates:
https://bugzilla.redhat.com/show_bug.cgi?id=2127506
https://github.com/stolostron/backlog/issues/25704
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Add an option to treat a JSON string as literal JSON

- pkg/templates/templates.go
- pkg/templates/templates_test.go
This prevents unexpected alterations in the YAML structure prior to the current indentation level.
Relates:
https://github.com/stolostron/backlog/issues/25704
> Disallow new lines passed to toLiteral

- go.mod
- go.sum
- pkg/templates/clusterconfig_funcs.go
- pkg/templates/encryption.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates.go
klog is a drop-in replacement of glog and is more compatible with container deployments and the rest of the Open Cluster Management Policy stack.
This also removes the default log level constant since that really should be a level 0 log and each log message should have a level explicitly chosen.
> Migrate from glog to klog

- go.mod
This is due to the breaking change in:
https://github.com/stolostron/go-template-utils/commit/f20c2295d55ff5e4e29b0ec623a847334400c1c3
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Bump the module version to v3

- pkg/templates/clusterconfig_funcs.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates_suite_test.go
- pkg/templates/templates_test.go
- test_data/crds/clusterclaim.yaml
This allows consumers to watch for objects that don't yet exist and
reexecute the templates when they do.
The second commit simplifies the `TestReferencedObjects` parameters.
Relates:
https://issues.redhat.com/browse/ACM-1936
> Return object references when the object does not exist

- build/common/config/.golangci.yml
- go.sum
- pkg/templates/templates.go
- pkg/templates/templates_test.go
Maybe I got overzealous organizing and improving some unit tests here... I can split this into two PRs if that would be preferred.
The real change to users is to allow maps inside of the context passed to the template. This enables uses like https://issues.redhat.com/browse/ACM-4168.
> Maps in template contexts

- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
Use the template feature to copy the data contents of a configmap or secret to another resource as defined in a policy.
Refs:
- https://issues.redhat.com/browse/ACM-2611
Signed-off-by: Gus Parvin <gparvin@redhat.com>
> Create functions to copy the data in configmap and secrets

- go.mod
- go.sum
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/templates_suite_test.go
Use Kubernetes  label selectors to filter results of the lookup function when returning a list of objects.
Refs:
- https://issues.redhat.com/browse/ACM-4855
Signed-off-by: Brian Jarvis <bjarvis@redhat.com>
> Enable use labels for template Lookup function

- experimental/client.go
- go.mod
- go.sum
- pkg/templates/clusterconfig_funcs.go
- pkg/templates/clusterconfig_funcs_test.go
- pkg/templates/encryption.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/sprig_wrapper_test.go
- pkg/templates/templates.go
- pkg/templates/templates_suite_test.go
- pkg/templates/templates_test.go
See each commit for changes.
The default caching mode is one that caches objects for the duration of the ResolveTemplate execution. This mode is not completely concurrency safe.
The advanced caching mode is concurrency safe and utilizes watches to update the cache in background goroutines.
Relates:
https://issues.redhat.com/browse/ACM-7398
> Add two caching modes

- experimental/client.go
- go.mod
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This is needed by the Policy Propagator since it processes its policy-templates array entries one at a time and we don't want to clean up stale API watches and cache entries until those are all processed.
The second commit bumps the version to v4.
> Allow control of when the cache and API watches are cleaned up

- pkg/templates/templates.go
This left query batches lingering if automatic cache clean up is disabled on errors.
Relates:
https://issues.redhat.com/browse/ACM-8928
> Return the cache cleanup function on errors

- go.mod
- go.sum
This uses the side branch of release-2.9.1 on
github.com/stolostron/kubernetes-dependency-watches to avoid package upgrades.
Relates:
https://issues.redhat.com/browse/ACM-8928
> [2.9] Update kubernetes-dependency-watches

- README.md
- experimental/template-resolver/client.go
- Allows `go install` to be run with the resulting binary named "template-resolver" (rather than "experimental")
- Adds positional argument usage if the `--help` flag is passed
- Adds manual help output to remove extra klog arguments
- Removes extra trailing newline from output
- Adds missing functions and converts function list to a table
(Regarding the CLI, I played around with adding a `go.mod`, but the `replace` directives prevented the resulting `go install` from working since it wasn't the main module.)
> Move CLI directory; Update README

- pkg/templates/templates.go
- pkg/templates/templates_test.go
This allows users that already have a DynamicWatcher and are using Query Batches to supply their instance to the template resolver. Most details of managing the watcher and the batch are delegated to the user: this package will not automatically stop the query batch after the template is resolved, for instance.
> Add constructor for pre-existing DynamicWatcher

- pkg/templates/generic_lookup_func.go
This prevents a user from accidentally modifying an object in the cache.
> Deep copy objects from the dynamic watcher

- pkg/templates/clusterconfig_funcs.go
- pkg/templates/encryption.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
If the template handled a secret or decrypted data in the template, the TemplateResult now has a field of HasSensitiveData set to true.
This is required as part of automatically determining if it's safe to record a diff in the config-policy-controller.
Relates:
https://issues.redhat.com/browse/ACM-11421
> Return if the templates contain sensitive data

- README.md
- go.mod
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/templates.go
- pkg/templates/templates_suite_test.go
https://issues.redhat.com/browse/ACM-12342
Adds two template functions to reduce complexity in Policies around identifying nodes by role, specifically useful for Infra nodes.
getNodesWithExactRoles - only returns nodes that have label "node-role.kubernetes.io/NAME"  and optionally "node-role.kubernetes.io/worker".  Nodes which have "node-role.kubernetes.io/NAME"  and any other role label are ignored.  Can pass multiple NAME parameters.
hasNodesWithExactRoles - returns true if getNodesWithRole returns more than zero nodes  for the specified role name(s) parameter.
> Add getNodesWithExactRoles and hasNodesWithExactRoles template functions

- cmd/template-resolver/client.go
- cmd/template-resolver/utils/templateResolver.go
- go.mod
- pkg/templates/templates.go
- pkg/templates/templates_test.go
Rather than the partial control of `DisableAutoCacheCleanUp` and `NewResolverWithDynamicWatcher`, this is simplified to either the batch is fully managed in the `ResolveTemplate` call or the caller completely controls the batch. 
This simplifies the API for most use cases.
Note that since this is a break change, the version is bumped.
Relates:
https://issues.redhat.com/browse/ACM-12790
> Allow full control of query batches

- pkg/templates/sprig_wrapper.go
This will allow consumers of the library to know what sprig functions are available.
> Export ExportedSprigFunctions

- cmd/template-resolver/utils/resolver_client.go
- Add description for the positional argument
- Add details on the `.ManagedClusterName`
- Add clearer message for stdin error handling
- Exit immediately with code 2 on template errors (to prevent the CLI usage from displaying)
ref: https://issues.redhat.com/browse/ACM-14630
> Update descriptions and error handling

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_custom-sa_hub/input.yaml
- cmd/template-resolver/testdata/test_custom-sa_hub/output.yaml
- cmd/template-resolver/testdata/test_obj_variable_config/input.yaml
- cmd/template-resolver/testdata/test_obj_variable_config/output.yaml
- cmd/template-resolver/testdata/test_obj_variable_operator/input.yaml
- cmd/template-resolver/testdata/test_obj_variable_operator/output.yaml
- cmd/template-resolver/testdata/test_object-templates-raw/input.yaml
- cmd/template-resolver/testdata/test_object-templates-raw/output.yaml
- cmd/template-resolver/utils/resolver_client.go
- cmd/template-resolver/utils/resolver_utils.go
- pkg/templates/templates.go
As a template-resolver user, I'd like a way to supply "ObjectNamespace" and "ObjectName" template variable values as CLI arguments to template-resolver like I can with the "--cluster-name" argument. This allows me to resolve templates locally that leverage these new template variables.
Ref: https://issues.redhat.com/browse/ACM-15971
> Add ObjectNamespace and ObjectName arguments

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_config-policy-directly/input.yaml
- cmd/template-resolver/testdata/test_config-policy-directly/save_resources.yaml
- cmd/template-resolver/testdata/test_config-policy-directly_hub/save_hub_resources.yaml
- cmd/template-resolver/testdata/test_custom-sa_hub/save_hub_resources.yaml
- cmd/template-resolver/testdata/test_label-configmaps/save_resources.yaml
- cmd/template-resolver/testdata/test_label-configmaps_hub/save_resources.yaml
- cmd/template-resolver/testdata/test_object-templates-raw/save_resources.yaml
- cmd/template-resolver/testdata/test_operator-policy-directly/save_resources.yaml
- cmd/template-resolver/testdata/test_operator-policy/save_resources.yaml
- cmd/template-resolver/testdata/test_operator-policy_hub/save_resources.yaml
- cmd/template-resolver/utils/resolver_client.go
- cmd/template-resolver/utils/resolver_utils.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/templates.go
The template resolver should output the full YAML of objects used in lookups, fromConfig, fromSecret, etc., allowing users to easily modify them for tests using dry-run.
Ref: https://issues.redhat.com/browse/ACM-17214
> Include the full YAML of the objects it uses in funcs

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_skipobject/input.yaml
- cmd/template-resolver/testdata/test_skipobject/output.yaml
- cmd/template-resolver/testdata/test_skipobject_multi_arg/error.txt
- cmd/template-resolver/testdata/test_skipobject_multi_arg/input.yaml
- cmd/template-resolver/testdata/test_skipobject_non_bool/error.txt
- cmd/template-resolver/testdata/test_skipobject_non_bool/input.yaml
- cmd/template-resolver/utils/resolver_utils.go
- testdata/crds.yaml
By returning a template string rather than skipping the template, this will allow passing to tools like `dryrun` to perform proper handling.
ref: https://issues.redhat.com/browse/ACM-19739
This PR will need to be followed up with one that adds arguments for ACM 2.14 for changes in:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/354
> Add `skipObject` custom function

- pkg/templates/sprig_wrapper.go
Aligns and groups the list with the Sprig doc website
In the process, I also discovered there's a forked Sprout library we might consider migrating to in the future: https://docs.atom.codes/sprout
> Reorganize the Sprig list by category

- pkg/templates/sprig_wrapper_test.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
With the `.Object` variable, Kubernetes objects could have a variety of kinds. Expand the context check to allow these kinds, avoiding pointers, channels, and functions that could disrupt or cause unexpected results in templates.
ref: https://issues.redhat.com/browse/ACM-20863
> Expand context kinds allowed

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_invalid-objdef-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-objdef/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/output.yaml
- cmd/template-resolver/utils/resolver_utils.go
- go.mod
The `unstructured` package made the decision to not support `int` types, but that's exactly what our YAML marshaler uses. Changing to type assertions avoids the panic.
ref: https://issues.redhat.com/browse/ACM-18816
> fix: Resolve panic when manifest has an `int`

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_invalid-objdef-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-objdef/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/output.yaml
- cmd/template-resolver/utils/resolver_utils.go
- go.mod
- testdata/crds.yaml
Manual cherry-pick:
- #203
ref: https://issues.redhat.com/browse/ACM-18816
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
> [release-2.13] fix: Resolve panic when manifest has an `int`

- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_invalid-objdef-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-objdef/error.txt
- cmd/template-resolver/testdata/test_invalid-objdef/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-spec/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-spec/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-bad-entry/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates-missing/input.yaml
- cmd/template-resolver/testdata/test_invalid-policy-templates/error.txt
- cmd/template-resolver/testdata/test_invalid-policy-templates/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/input.yaml
- cmd/template-resolver/testdata/test_policy-policy-templates-int/output.yaml
- cmd/template-resolver/utils/resolver_utils.go
- go.mod
- testdata/crds.yaml
Manual cherry-pick:
- #203 
ref: https://issues.redhat.com/browse/ACM-18816
> [release-2.12] fix: Resolve panic when manifest has an `int`

- Makefile
- cmd/template-resolver/client_test.go
- cmd/template-resolver/testdata/test_linting_mismatched_delimiters_hub/config.yaml
- cmd/template-resolver/testdata/test_linting_mismatched_delimiters_hub/error.txt
- cmd/template-resolver/testdata/test_linting_mismatched_delimiters_hub/input.yaml
- cmd/template-resolver/testdata/test_linting_multiple_errors/config.yaml
- cmd/template-resolver/testdata/test_linting_multiple_errors/error.txt
- cmd/template-resolver/testdata/test_linting_multiple_errors/input.yaml
- cmd/template-resolver/testdata/test_linting_trailing_whitespace/config.yaml
- cmd/template-resolver/testdata/test_linting_trailing_whitespace/input.yaml
- cmd/template-resolver/testdata/test_linting_trailing_whitespace/output.yaml
- cmd/template-resolver/testdata/test_linting_unquoted_values/config.yaml
- cmd/template-resolver/testdata/test_linting_unquoted_values/error.txt
- cmd/template-resolver/testdata/test_linting_unquoted_values/input.yaml
- cmd/template-resolver/testdata/test_linting_valid_template_hub/config.yaml
- cmd/template-resolver/testdata/test_linting_valid_template_hub/input.yaml
- cmd/template-resolver/testdata/test_linting_valid_template_hub/output.yaml
- cmd/template-resolver/utils/resolver_client.go
- cmd/template-resolver/utils/resolver_utils.go
- pkg/templates/lint.go
- testdata/crds.yaml
Adds a `--lint` argument to the `template-resolver` to output linting issues along with the output. Linting output is to stderr, so can be filtered out if it raises issues that might be associated with a valid template. The new `lint.go` file contains separate lint functions and then iterates over them, so adding a new linting rule function is relatively straightforward.
I didn't track which ones I've covered here in this PR, but this doc is a collection of linting messages that I had been compiling that could serve as a guide to new rules to add: https://docs.google.com/document/d/1dVmpTgwy7AySYa3ScCr1FE0P_G1uBpLRXLeA94i97dw/edit?tab=t.0#heading=h.xac5cv9qxxk6
I debated having a subcommand, but I think toggling it on/off makes sense and is convenient. Currently the linting isn't aware …
> feat: implement template linter in template-resolver

- cmd/template-resolver/utils/resolver_client.go
I realized I had it backward seeing @jan-law's work: https://github.com/open-cluster-management-io/config-policy-controller/pull/388/files#r2395966681
> fix: allow the `--lint` arg to override the env
