stolostron/go-template-utils

- pkg/templates/generic_lookup_func.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
Resolves https://github.com/open-cluster-management/backlog/issues/15300
> Allow restricting template lookup functions to a specific namespace

- Makefile
- build/common/config/.golangci.yml
- pkg/templates/clusterconfig_funcs_test.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/k8sresource_funcs.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
Resolves:
https://github.com/open-cluster-management/backlog/issues/18038
> Configure linting to conform with the team's standards

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- build/common/Makefile.common.mk
- build/common/config/.golangci.yml
- go.mod
- https://github.com/stolostron/backlog/issues/17978
> Organization rename to `stolostron`

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- build/common/Makefile.common.mk
- go.mod
- https://github.com/stolostron/backlog/issues/17978
> [release-2.4] Organization rename to `stolostron`

- pkg/templates/k8sresource_funcs.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This is a more secure and typical implementation of AES-CBC encryption.
> Replace the salt config with a custom initialization vector

- pkg/templates/templates.go
> Add documentation for `SetEncryptionConfig`

- pkg/templates/templates.go
- pkg/templates/templates_test.go
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
Related Issue : https://github.com/stolostron/backlog/issues/19307
> Add int,bool support for multiple clause templates

- Makefile
(The primary goal here is to test the SonarCloud scan.)
> Minor edits

- .github/workflows/sonarcloud.yml
- .github/workflows/unit-tests.yml
- .gitignore
- Makefile
Relates:
https://github.com/stolostron/backlog/issues/25949
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Run SonarCloud on PRs and pushes

- .ci-operator.yaml
- build/common/config/.golangci.yml
- go.mod
- pkg/templates/templates.go
- https://github.com/stolostron/backlog/issues/26293
> Update to Go 1.19

- README.md
- pkg/templates/templates.go
- pkg/templates/templates_test.go
This backports #64 and #70.
Relates:
https://github.com/stolostron/backlog/issues/25704
> Backport the toLiteral template function

- .ci-operator.yaml
- build/common/config/.golangci.yml
- go.mod
- pkg/templates/templates.go
ref: https://github.com/stolostron/backlog/issues/27048
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
> [release-2.5] Upgrade to Go 1.19

- OWNERS
- build/common/Makefile.common.mk
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
> [release-2.7] Update OWNERS

- .gitignore
- README.md
- experimental/client.go
- pkg/templates/templates.go
- pkg/templates/templates_test.go
- sonar-project.properties
This will help local development of policies. Since it's not going into the product and it's experimental, tests were not added.
> Add an experimental CLI

- pkg/templates/templates.go
- pkg/templates/templates_test.go
The allowed types for the template context (i.e. variables) are structs, map[string]string, strings, and a recursive combination of the above.
This is to allow a template variable that contains a subset of the Kubernetes metadata field (i.e. a map with string and map[string]string values).
Relates:
https://issues.redhat.com/browse/ACM-12566
> Loosen template context restrictions

- pkg/templates/generic_lookup_func.go
Relates:
https://issues.redhat.com/browse/ACM-13346
> Unset the namespace for cluster scoped resources

- cmd/template-resolver/utils/resolver_client.go
> `templateresolver` --> `template-resolver`

- .ci-operator.yaml
- go.mod
ref: https://issues.redhat.com/browse/ACM-14251
> [release-2.10] Update to Go v1.22

- .ci-operator.yaml
- go.mod
ref: https://issues.redhat.com/browse/ACM-14251
> Update to Go v1.22

- .ci-operator.yaml
- go.mod
ref: https://issues.redhat.com/browse/ACM-14251
> [release-2.11] Update to Go v1.22

- cmd/template-resolver/testdata/setup/random.namespace.yaml
- cmd/template-resolver/testdata/test_custom-sa_hub/input.yaml
- cmd/template-resolver/testdata/test_custom-sa_hub/output.yaml
- cmd/template-resolver/testdata/test_label-configmaps_hub/input.yaml
- cmd/template-resolver/testdata/test_label-configmaps_hub/output.yaml
- cmd/template-resolver/utils/resolver_utils.go
See each commit for more details.
> Add 2.12 hub template features to template-resolver

- cmd/template-resolver/testdata/setup/local-cluster.managedcluster.yaml
- cmd/template-resolver/testdata/setup/operator-config.yaml
- cmd/template-resolver/testdata/test_operator-policy-directly/input.yaml
- cmd/template-resolver/testdata/test_operator-policy-directly/output.yaml
- cmd/template-resolver/testdata/test_operator-policy/input.yaml
- cmd/template-resolver/testdata/test_operator-policy/output.yaml
- cmd/template-resolver/testdata/test_operator-policy_hub/input.yaml
- cmd/template-resolver/testdata/test_operator-policy_hub/output.yaml
- cmd/template-resolver/utils/resolver_client.go
- cmd/template-resolver/utils/resolver_utils.go
For https://issues.redhat.com/browse/ACM-13340
> Resolve OperatorPolicies

- pkg/templates/templates.go
- pkg/templates/templates_test.go
Relates:
https://issues.redhat.com/browse/ACM-15937
> Add a resolve option for custom template functions

- cmd/template-resolver/utils/resolver_utils.go
> #176 Fix pipe stdin

- .ci-operator.yaml
- .github/workflows/linters.yml
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.13] Address `oauth2` vuln

- .ci-operator.yaml
- go.mod
- go.sum
> Address `oauth2` vuln

- .ci-operator.yaml
- .github/workflows/linters.yml
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.11] Address `oauth2` vuln

- .ci-operator.yaml
- .github/workflows/linters.yml
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.10] Address `oauth2` vuln

- pkg/templates/sprig_wrapper.go
- pkg/templates/sprig_wrapper_test.go
ref: https://issues.redhat.com/browse/ACM-19745
> Add `fail` function

- pkg/templates/sprig_wrapper_test.go
- pkg/templates/templates.go
...because `toRawJson` and `fromJson` has always confused me.
> Add uppercase JSON functions

- .ci-operator.yaml
- build/common/Makefile.common.mk
- build/common/config/.golangci.yml
- cmd/template-resolver/cmd_suite_test.go
- cmd/template-resolver/utils/resolver_client.go
- cmd/template-resolver/utils/resolver_utils.go
- go.mod
- pkg/templates/clusterconfig_funcs_test.go
- pkg/templates/encryption.go
- pkg/templates/generic_lookup_func.go
- pkg/templates/generic_lookup_func_test.go
- pkg/templates/k8sresource_funcs_test.go
- pkg/templates/sprig_wrapper_test.go
- pkg/templates/templates.go
- pkg/templates/templates_suite_test.go
- pkg/templates/templates_test.go
- testdata/crds.yaml
ref: https://issues.redhat.com/browse/ACM-24264
> [release-2.13] Update to Go v1.24
